name       : alembic
version    : 1.8.2
release    : 2
source     :
    - https://github.com/alembic/alembic/archive/refs/tags/1.8.2.tar.gz : 3f1c466ee1600578689b32b1f2587066d3259704ec7ed1fcf80c324d01274f48
license    : BSD-3-Clause
homepage   : https://www.alembic.io/
component  : programming.library
summary    : Framework for storing and sharing scene data
description: |
    Alembic is an open framework for storing and sharing scene data that includes a C++ library, a file format, and client plugins and applications.
builddeps  :
    - pkgconfig(Imath)
    - pkgconfig(hdf5)
    - libboost-devel
rundeps    :
    - devel :
        - imath-devel
setup      : |
    %cmake_ninja -DUSE_HDF5=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
