name       : alembic
version    : 1.8.3
release    : 3
source     :
    - https://github.com/alembic/alembic/archive/refs/tags/1.8.3.tar.gz : b0bc74833bff118a869e81e6acb810a58797e77ef63143954b2f8e817c7f65cb
license    : BSD-3-Clause
homepage   : https://www.alembic.io/
component  : programming.library
summary    : Framework for storing and sharing scene data
description: |
    Alembic is an open framework for storing and sharing scene data that includes a C++ library, a file format, and client plugins and applications.
builddeps  :
    - pkgconfig(Imath)
    - pkgconfig(hdf5)
    - libboost-devel
rundeps    :
    - devel :
        - imath-devel
setup      : |
    %cmake_ninja -DUSE_HDF5=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
