name       : alembic
version    : 1.7.16
release    : 1
source     :
    - https://github.com/alembic/alembic/archive/1.7.16.tar.gz : 2529586c89459af34d27a36ab114ad1d43dafd44061e65cfcfc73b7457379e7c
license    : BSD-3-Clause
homepage   : https://www.alembic.io/
component  : programming.library
summary    : Framework for storing and sharing scene data
description: |
    Alembic is an open framework for storing and sharing scene data that includes a C++ library, a file format, and client plugins and applications.
builddeps  :
    - pkgconfig(OpenEXR)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
